### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by lantzj** [pinbackit/pinback#10]
I just installed this, and when I click it it says to log in and visit my profile (pinterest.com/username) to start.  I've logged out of Pinterest and logged back in.  I'm on my profile.  But I can't seem to get the Pinback to recognize it.  I'm using Chrome.   Any suggestions?

**Comment by lantzj** [comment]
Also, I've tried to install it in EDGE and it will not drag to the bookmarks bar.   It keeps the red circle with a line through it so it won't install.   So I can't test it on my other browser.

**Comment by ghost** [comment]
Hi! I'm having the same issue, any solution?

I get the message "Log in and visit your profile to start (pinterest.com/username)" on Chrome using macOS.

**Comment by pinbackit** [comment]
v0.4.0 should fix it: https://pinbackit.github.io/ 👍
