### ISSUE TITLE
FWIW, to make it work, I had to...

### ISSUE THREAD

**Issue by oluc** [pinbackit/pinback#4]
FWIW,
to make it work, I had to
- remove the `//` comment lines
- don't use `\` in strings
- add a `;` to close the statement `if (!boards[p.board.name]) boards[p.board.name] = { ... }`
- change the CSS selectors
  - checking if on the boards page: .userBoards
  - waiting for all board links to load: .secretBoardWrapper
  - selecting each board: .ProfileBoardCard
- add a prefix 'javascript:'

then I could copy/paste into the 'Location' field of a new bookmark (firefox).

**Comment by inudder** [comment]
HI. Pinback It doesn`t work, i try in firefox and chrome.. Why? Help me 

** @oluc**

**Comment by jdsimcoe** [comment]
@oluc Can you share a Gist or snippet of the fixed code somewhere?

**Comment by ghost** [comment]
@oluc I tried what you suggested and it's not working. Could you please post the modified code?

**Comment by stormfar** [comment]
@oluc another request for a gist of the modified code please

**Comment by oluc** [comment]
I don't have it anymore. sorry.

**Comment by pinbackit** [comment]
We released a proper fix in v0.3, you'll just need to re-install the bookmarklet: http://www.pinback.it/

cc @oluc @5tormTrooper @tfarmerjr @jdsimcoe
