### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by exoloner** [pinbackit/pinback#5]
Succefully Added the bookmarklet to the bookmarks bar.
login into my pinterest account, I go to my profile 

pinterest.com/nnnnnnnnnn
An then i click on the bookmarklet and nothing happens.
Note that if I'm not in my profile, the click forces the browser to go to my pinterest home profile page.

Using lastest versions of : Opera, Chrome, Mozilla, IE11
Is any way to trace or debug this?

**Comment by exoloner** [comment]
Also JS Console reports this 

Use of Mutation Events is deprecated. Use MutationObserver instead.  ((function()%7Bfunction%20e()%7Bdocument.querySelector(%22.boardLinkWrapper%22)%26%26(document.removeEventListener(%22DOMNodeInserted%22%2Ce)%2Ct())%7Dfunction%20t()%7Bif(document.querySelector(%22%23pboverlay%22))return!1%3Bwindow.scrollTo(0%2C0)%3Bvar%20e%3Ddocument.createElement(%22div%22)%3Be.id%3D%22pboverlay%22%2Ce.innerHTML%3D%27%3Cstyle%3E%20%20%23pboverlay%20%7B%20display%3A%20block%3B%20bottom%3A%200%3B%20left%3A%200%3B%20right%3A%200%3B%20top%3A%200%3B%20z-index%3A%209999%3B%20position%3A%20fixed%3B%20background%3A%20rgba(0%2C%200%2C%200%2C%200.8)%3B%20color%3A%20white%3B%20text-align%3A%20center%3B%20%7D%20%20%23pboverlay%20.close%20%7B%20color%3A%20white%3B%20position%3A%20absolute%3B%20top%3A10px%3B%20right%3A20px%3B%20font-size%3A%2030px%3B%20%7D%20%20%23pboverlay%20.standardForm%20%7B%20top%3A%2050%25%3B%20margin-top%3A%20-100px%3B%20position%3A%20absolute%3B%20width%3A%20100%25%3B%20max-width%3A%20none%3B%20%7D%20%20%23pboverlay%20h1%20%7B%20color%3A%20white%3B%20%7D%20%20%23pboverlay%20.controls%20a%20%7B%20display%3A%20inline-block%3B%20%7D%20%20%23pboverlay%20select%2C%20%23pboverlay%20meter%20%7B%20width%3A%20100%25%3B%20max-width%3A%20300px%3B%20!important%20%7D%20%20%23pboverlay%20.btn%20%7B%20-webkit-box-shadow%3A%200%201px%200%200%20rgba(0%2C%200%2C%200%2C%200.34)%20!important%3B%20box-shadow%3A%200%201px%200%200%20rgba(0%2C%200%2C%200%2C%200.34)%20!important%3B%20margin-left%3A%2010px%3B%7D%3C%2Fstyle%3E%3Ca%20href%3D%22%23%22%20class%3D%22close%22%3E%26times%3B%3C%2Fa%3E%3Cform%20class%3D%22standardForm%22%3E%20%20%3Ch1%3EChoose%20a%20board%20to%20export%3C%2Fh1%3E%20%20%3Cp%20class%3D%22controls%22%3E%20%20%20%20%3Cselect%3E%3C%2Fselect%3E%20%20%20%20%3Cbutton%20class%3D%22Button%20btn%20rounded%20primary%22%3E%20%20%20%20%20%20%3Cspan%20class%3D%22buttonText%22%3EExport%3C%2Fspan%3E%20%20%20%20%3C%2Fbutton%3E%20%20%3C%2Fp%3E%20%20%3Cp%3E%3Ca%20href%3D%22http%3A%2F%2Fwww.pinback.it%22%3EPinback%20v%27%2Bu%2B%22%3C%2Fa%3E%3C%2Fp%3E%3C%2Fform%3E%22%2Cdocument.querySelector(%22body%22).appendChild(e)%3Bvar%20t%3Ddocument.querySelector(%22%23pboverlay%20select%22)%2Cn%3Ddocument.createElement(%22option%22)%3Bn.text%3D%22%20-%20All%20public%20pins%20-%20%22%2Cn.value%3D%22%2F%22%2Blocation.pathname.split(%22%2F%22)%5B1%5D%2B%22%2Fpins%2F%22%2Cn.dataset.name%3D%22all%20public%20pins%22%2Ct.add(n)%2CArray.prototype.forEach.call(document.querySelectorAll(%22.boardLinkWrapper%22)%2Cfunction(e%2Co)%7Bvar%20r%3De.querySelector(%22.name%22).innerText%2Cn%3Ddocument.createElement(%22option%22)%3Bn.text%3Dr%2Cn.value%3De.getAttribute(%22href%22)%2Cn.dataset.name%3Dr%2Cn.selected%3Dl%3D%3De.href%2Ct.add(n)%7D)%2Cdocument.querySelector(%22%23pboverlay%20button%22).onclick%3Dfunction()%7Bvar%20e%3Dt.querySelector(%22option%3Achecked%22)%2Co%3De.dataset.name%2Cn%3Ddocument.querySelector(%27a%5Bhref%3D%22%27%2Be.value%2B%27%22%5D%27)%3Breturn%20n.href%3De.value%2B%22%3F%22%2BDate.now()%2Cn.click()%2Cr(%22Exporting%20%22%2Bo%2B%22...%22)%2Cdocument.querySelector(%22%23pboverlay%20.controls%22).innerHTML%3D%27%3Cmeter%20min%3D%220%22%20max%3D%22100%22%3E%3C%2Fmeter%3E%27%2C!1%7D%2Cdocument.querySelector(%22%23pboverlay%20.close%22).onclick%3Dfunction()%7Breturn%20window.scrollTo(0%2C0)%2Clocation.href%3Dlocation.pathname%2C!1%7D%2CXMLHttpRequest.prototype.send%3Dfunction(e)%7Breturn%20function()%7Breturn%20this.addEventListener(%22loadend%22%2Cfunction(e)%7Bif(e.target.getResponseHeader(%22content-type%22).match(%2Fjson%2F))%7Bvar%20t%3DJSON.parse(e.target.response)%3Bt.resource%26%26t.resource_response%26%26t.resource_response.data%3Fo(t.resource%2Ct.resource_response.data)%3At.resource_data_cache%26%26t.resource_data_cache.forEach(function(e%2Ct)%7Be.resource%26%26o(e.resource%2Ce.data)%7D)%7D%7D%2C!1)%2Ce.apply(this%2Carguments)%7D%7D(XMLHttpRequest.prototype.send)%7Dfunction%20o(e%2Ct)%7Bif((%22UserResource%22%3D%3De.name%7C%7C%22BoardResource%22%3D%3De.name)%26%26(d%3Dt%2Cm%3D%5B%5D)%2C%22UserPinsResource%22%3D%3De.name%7C%7C%22BoardFeedResource%22%3D%3De.name)%7Bt.forEach(function(e%2Ct)%7B%22pin%22%3D%3De.type%26%26(s%5Be.board.name%5D%7C%7C(s%5Be.board.name%5D%3D%7Bid%3Ae.board.id%2Cname%3Ae.board.name%2Curl%3A%22https%3A%2F%2Fwww.pinterest.com%22%2Be.board.url%2Cprivacy%3Ae.board.privacy%2Cpins%3A%5B%5D%7D)%2Cs%5Be.board.name%5D.pins.push(%7Bid%3Ae.id%2Clink%3Ae.link%2Cdescription%3Ae.description%2Curl%3A%22https%3A%2F%2Fwww.pinterest.com%2Fpin%2F%22%2Be.id%2Cimage%3Ae.images.orig.url%2Ccolor%3Ae.dominant_color%2Clongitude%3Ae.place%26%26e.place.longitude%7C%7Cnull%2Clatitude%3Ae.place%26%26e.place.latitude%7C%7Cnull%2Cpinner%3Ae.pinner.username%2Cprivacy%3Ae.privacy%2Cdate%3ADate.parse(e.created_at)%7D)%2Cy%2B%2B)%7D)%2Cn(y%2Cd.pin_count)%3Bvar%20o%3D%22undefined%22!%3Dtypeof%20e.options.bookmarks%3Fe.options.bookmarks%5B0%5D%3Anull%3Bp%26%26clearTimeout(p)%2Cy%3E%3Dd.pin_count%7C%7C%22-end-%22%3D%3Do%3Fy%3E0%26%26i()%3Ap%3DsetTimeout(function()%7Bwindow.scrollTo(0%2Cdocument.body.scrollHeight)%7D%2Cb)%7D%7Dfunction%20r(e)%7Bdocument.querySelector(%22%23pboverlay%20h1%22).innerText%3De%7Dfunction%20n(e%2Ct)%7Br(%22Exporting%20%22%2Be%2B%22%20of%20%22%2Bt%2B%22...%22)%2Cdocument.querySelector(%22%23pboverlay%20meter%22).value%3De%2Ft*100%7Dfunction%20a(e)%7Breturn%22public%22!%3De%3F1%3A0%7Dfunction%20c(e)%7Breturn%20e.replace(%2F%26%2Fg%2C%22%26amp%3B%22).replace(%2F%3C%2Fg%2C%22%26lt%3B%22).replace(%2F%3E%2Fg%2C%22%26gt%3B%22).replace(%2F%22%2Fg%2C%22%26quot%3B%22).replace(%2F%27%2Fg%2C%22%26%23039%3B%22)%7Dfunction%20i()%7Br(%22Export%20complete!%22)%3Bvar%20e%3D%27%3C!DOCTYPE%20NETSCAPE-Bookmark-file-1%3E%5Cn%3CMETA%20HTTP-EQUIV%3D%22Content-Type%22%20CONTENT%3D%22text%2Fhtml%3B%20charset%3DUTF-8%22%3E%5Cn%3CTITLE%3EBookmarks%3C%2FTITLE%3E%5Cn%3CH1%3EBookmarks%3C%2FH1%3E%5Cn%3CDL%3E%3Cp%3E%5Cn%27%3Bfor(var%20t%20in%20s)%7Bvar%20o%3Ds%5Bt%5D%3Be%2B%3D%27%3CDT%3E%3CH3%20GUID%3D%22%27%2Bo.id%2B%27%22%20ORIGLINK%3D%22%27%2Bo.url%2B%27%22%20PRIVATE%3D%22%27%2Ba(o.privacy)%2B%27%22%3E%27%2Bc(o.name)%2B%22%3C%2FH3%3E%5Cn%3CDL%3E%3Cp%3E%5Cn%22%2Co.pins.forEach(function(t%2Co)%7Be%2B%3D%27%3CDT%3E%3CA%20HREF%3D%22%27%2B(t.link%7C%7Ct.url)%2B%27%22%20GUID%3D%22%27%2Bt.id%2B%27%22%20ORIGLINK%3D%22%27%2Bt.url%2B%27%22%20IMAGE%3D%22%27%2Bt.image%2B%27%22%20COLOR%3D%22%27%2Bt.color%2B%27%22%20AUTHOR%3D%22%27%2Bt.pinner%2B%27%22%20PRIVATE%3D%22%27%2Ba(t.privacy)%2B%27%22%20ADD_DATE%3D%22%27%2Bt.date%2B%27%22%20LONGITUDE%3D%22%27%2B(t.longitude%7C%7C%22%22)%2B%27%22%20LATITUDE%3D%22%27%2B(t.latitude%7C%7C%22%22)%2B%27%22%3E%27%2Bc(t.description)%2B%22%3C%2FA%3E%5Cn%22%7D)%2Ce%2B%3D%22%3C%2FDL%3E%3Cp%3E%5Cn%22%7De%2B%3D%22%3C%2FDL%3E%3Cp%3E%22%3Bvar%20n%3Dlocation.pathname.replace(%2F%5E%5C%2F%7C%5C%2F%24%2Fg%2C%22%22).replace(%2F%5C%2F%2Fg%2C%22-%22)%2B%22.html%22%2Ci%3Dnew%20Blob(%5Be%5D%2C%7Btype%3A%22text%2Fhtml%22%7D)%2Cl%3DURL.createObjectURL(i)%3Bdocument.querySelector(%22%23pboverlay%20.controls%22).innerHTML%3D%27%3Ca%20href%3D%22%27%2Bl%2B%27%22%20download%3D%22%27%2Bn%2B%27%22%20class%3D%22Button%20btn%20rounded%20primary%22%3E%3Cspan%20class%3D%22buttonText%22%3ESave%20export%20file%3C%2Fspan%3E%3C%2Fa%3E%27%2C%22undefined%22%3D%3Dtypeof%20document.createElement(%22a%22).download%26%26(document.querySelector(%22%23pboverlay%20.controls%20a%22).onclick%3Dfunction()%7Balert(%22Choose%20File%20%3E%20Save%20As%20in%20your%20browser%20to%20save%20a%20copy%20of%20your%20export%22)%7D)%7Dvar%20l%2Cp%2Cu%3D%220.2%22%2Cs%3D%7B%7D%2Cd%3D%7B%7D%2Cm%3D%5B%5D%2Cy%3D0%2Cb%3D1e3%3Bif(!location.hostname.match(%2Fpinterest.com%24%2F)%7C%7C!document.querySelector(%22.usernameLink%22))return%20alert(%22Log%20in%20and%20visit%20your%20profile%20to%20start%20(pinterest.com%2Fusername)%22)%2C!1%3Bif(document.querySelector(%22.boardLinkWrapper%22))t()%3Belse%7Bvar%20f%3Ddocument.querySelector(%22.profileSource%2C%20.BoardCount%2C%20.usernameLink%22)%3Bl%3Dlocation.href%2Cdocument.addEventListener(%22DOMNodeInserted%22%2Ce)%2Cf.click()%7

**Comment by pinbackit** [comment]
@exoloner Try upgrading to v0.3, you'll need to re-install the bookmarklet: http://www.pinback.it/

**Comment by exoloner** [comment]
Argg! They changed from pinterest.com to pinterest.ie ...0.3 not working
again.

2017-07-28 0:23 GMT+02:00 Pinback <notifications@github.com>:

**Comment by pinbackit** [comment]
@exoloner Ah good find, try upgrading to 0.3.1 for the regional domain fix: http://www.pinback.it/ 👍

**Comment by exoloner** [comment]
thanks! yes yes! in the future if they keep changing the domain name, or
whatever they put, based on browser regional stuff. : User might manually
replace your hardcoded pinterest.com to the pinterest.ie or pinterest.com
altering the bookmarklet JS code.
runs ok for me. thanks!

2017-08-02 18:04 GMT+02:00 Pinback <notifications@github.com>:
