### ISSUE TITLE
Doesn't currently seem to work

### ISSUE THREAD

**Issue by lyramisu** [pinbackit/pinback#7]
In both Chrome (Windows 7 Professional) and Safari (Sierra 10.12.6), clicking on this from the bookmarks bar while signed in to Pinterest and on my profile page just brings up a message saying to go to my profile page and sign in to begin. But I already signed in, and I am on my profile page.

When doing the same thing in Firefox (Windows 7 Professional) nothing happens. 

I last used pinbackit about 6 months ago on the Windows 7 Professional machine with no issues.

**Comment by pinbackit** [comment]
v0.4.0 should fix it: https://pinbackit.github.io/ 👍
