### ISSUE TITLE
Not working in Firefox Nightly & Chrome

### ISSUE THREAD

**Issue by SystemsOperator** [pinbackit/pinback#8]
Chrome: Version 67.0.3396.99, Windows
Firefox Nightly: 63.0a1 (2018-07-19)

In Firefox, nothing happens when clicking on the bookmarklet.

In Chrome, a pop-up notification: "www.pinterest.com says Log in and visit your profile to start (pinterest.com/username)" even though that's exactly the page that's loaded, already.

**Comment by pinbackit** [comment]
@SystemsOperator Try v0.4.0: https://pinbackit.github.io/
