### ISSUE TITLE
Not working due to missing page var

### ISSUE THREAD

**Issue by abaglione** [pinbackit/pinback#9]
Looks like profileBoardsFeed is no longer a variable on the user's profile page, so clicking the pinback bookmarks button will trigger the "Log in and visit your profile to start (pinterest.com/username)" message even if the user is already on their profile page.

**Comment by ghost** [comment]
Yes, I'm having the same issue.

**Comment by pinbackit** [comment]
@abaglione @brunofujii v0.4.0 should fix it: https://pinbackit.github.io/ 👍
